### ISSUE TITLE
crash while trying to run gateway

### ISSUE THREAD

**Issue by spiralw** [tatsuworks/gateway#41]
hi, i tried to run the gateway, but it throws errors related to parsing ETF for guilld create, and then panics and crashes entirely:
i'm not familiar with ETF so not sure what is happening here

```
root@bot:~/gateway/cmd/gateway# ./gateway --token "mytoken"
2022-11-12 22:19:10.485 [ERROR] <main.go:88>    profiler could not start        {"err": "project ID must be specified in the configuration if running outside of GCP"}
2022-11-12 22:19:10.504 [INFO]  <main.go:156>   starting manager        {"shards": 1, "start": 0, "stop": 1, "redis_host": "localhost:6379", "etcd_host": "http://localhost:2379,http://localhost:4001"}
2022-11-12 22:19:10.507 [INFO]  <manager.go:107>        starting shard  {"shard": 0, "total": 1}
2022-11-12 22:19:10.515 [INFO]  <manager.go:153>        attempting shard connect        {"shard": 0}
2022-11-12 22:19:10.516 [INFO]  <ws.go:178>     encoding        {"name": "gateway", "shard": 0, "name": "etf"}
2022-11-12 22:19:10.665 [INFO]  <ws.go:228>     sending identify        {"name": "gateway", "shard": 0}
2022-11-12 22:19:10.666 [INFO]  <ws.go:241>     websocket connected, waiting for events {"name": "gateway", "shard": 0}
2022-11-12 22:19:10.953 [INFO]  <ws.go:363>     ready   {"name": "gateway", "shard": 0, "sess": "cfd1dbd112ddf24da0987d80a3556b97", "guild_count": 0}
2022-11-12 22:19:10.960 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:285
             - expected bytes 100/109, got 120:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readAtomWithTag
                   /root/gateway/discord/discordetf/gen.go:159
2022-11-12 22:19:10.961 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:285
             - expected bytes 100/109, got 23:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readAtomWithTag
                   /root/gateway/discord/discordetf/gen.go:159
2022-11-12 22:19:10.962 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:285
             - expected bytes 100/109, got 23:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readAtomWithTag
                   /root/gateway/discord/discordetf/gen.go:159
2022-11-12 22:19:10.962 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read term:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:302
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readRawMap
                   /root/gateway/discord/discordetf/decoder.go:541
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - unknown type: [0]:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:515
2022-11-12 22:19:10.963 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:285
             - expected bytes 100/109, got 23:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readAtomWithTag
                   /root/gateway/discord/discordetf/gen.go:159
2022-11-12 22:19:10.968 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:285
             - expected bytes 100/109, got 0:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readAtomWithTag
                   /root/gateway/discord/discordetf/gen.go:159
2022-11-12 22:19:10.968 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read term:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:302
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readRawMap
                   /root/gateway/discord/discordetf/decoder.go:541
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - unknown type: [0]:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:515
2022-11-12 22:19:10.969 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read term:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:302
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readRawMap
                   /root/gateway/discord/discordetf/decoder.go:541
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - unknown type: [0]:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:515
2022-11-12 22:19:10.982 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:285
             - expected bytes 100/109, got 23:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readAtomWithTag
                   /root/gateway/discord/discordetf/gen.go:159
2022-11-12 22:19:10.982 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read term:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:302
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readRawMap
                   /root/gateway/discord/discordetf/decoder.go:541
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - unknown type: [0]:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:515
2022-11-12 22:19:10.983 [ERROR] <ws.go:267>     handle state event      {"name": "gateway", "shard": 0} ...
  "error": parse guild create:
               github.com/tatsuworks/gateway/handler.(*Client).GuildCreate
                   /root/gateway/handler/guild.go:14
             - find guild id:
               github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate
                   /root/gateway/discord/discordetf/guild.go:23
             - read term:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap
                   /root/gateway/discord/discordetf/decoder.go:302
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - read map key:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readRawMap
                   /root/gateway/discord/discordetf/decoder.go:541
             - read raw term into buf:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:519
             - unknown type: [0]:
               github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm
                   /root/gateway/discord/discordetf/decoder.go:515
panic: runtime error: slice bounds out of range [:1635279359] with capacity 20251

goroutine 51 [running]:
github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).read(...)
        /root/gateway/discord/discordetf/decoder.go:38
github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).readTerm(0xc0004e93b8?)
        /root/gateway/discord/discordetf/decoder.go:490 +0x36d
github.com/tatsuworks/gateway/discord/discordetf.(*etfDecoder).idFromMap(0xc0004e93b8, {0xd8774e, 0x2})
        /root/gateway/discord/discordetf/decoder.go:300 +0x18a
github.com/tatsuworks/gateway/discord/discordetf.decoder.DecodeGuildCreate({}, {0xc000258000?, 0x4f45?, 0xc0004e9470?})
        /root/gateway/discord/discordetf/guild.go:21 +0xc7
github.com/tatsuworks/gateway/handler.(*Client).GuildCreate(0xc000384090, {0xf07c58?, 0xc000478100}, {0xc000258000?, 0x0?, 0x13?})
        /root/gateway/handler/guild.go:12 +0x51
github.com/tatsuworks/gateway/handler.(*Client).HandleEvent(0xc0000c4900?, {0xf07c58, 0xc000478100}, 0xc0005aea80)
        /root/gateway/handler/helpers.go:23 +0x12b
github.com/tatsuworks/gateway/internal/gatewayws.(*Session).Open(0xc0000c4900, {0xf07c58, 0xc000478100}, {0x1?, 0x0?})
        /root/gateway/internal/gatewayws/ws.go:265 +0x129d
github.com/tatsuworks/gateway/internal/manager.(*Manager).startShard.func1()
        /root/gateway/internal/manager/manager.go:154 +0x19c
created by github.com/tatsuworks/gateway/internal/manager.(*Manager).startShard
        /root/gateway/internal/manager/manager.go:145 +0x372
root@bot-01:~/gateway/cmd/gateway#
```

**Comment by Aericio** [comment]
It seems like you're using FDB for state. We haven't updated that in *years*, so it definitely doesn't work anymore.

If you want to test this out without much fixing, use postgres db instead.
`./gateway --token "mytoken" --psqlAddr "postgres://xxx"`

**Comment by spiralw** [comment]
oh i see, the postgres state code connects to the json gateway instead of etf. are you not using etf anymore in your production?

it seems like using postgres mostly works correctly (the cache fills up, and i can get events in redis) but after 10 seconds it closes the gateway connection with the following error

```
2022-11-13 02:05:33.198 [ERROR] <read.go:21>    took too long to get reader     {"name": "gateway", "shard": 0, "took": "10.000679152s"}
2022-11-13 02:05:33.198 [ERROR] <ws.go:247>     read and decode event   {"name": "gateway", "shard": 0} ...
  "error": read message:
               github.com/tatsuworks/gateway/internal/gatewayws.(*Session).readAndDecodeEvent
                   /root/gateway/internal/gatewayws/ws.go:435
             - get ws reader:
               github.com/tatsuworks/gateway/internal/gatewayws.(*Session).readMessage
                   /root/gateway/internal/gatewayws/read.go:30
             - failed to get reader: WebSocket closed: read timed out: context deadline exceeded
```

is this because discord is not sending any events in the last 10 seconds? i'm trying this on a small test bot right now

**Comment by Aericio** [comment]
> are you not using etf anymore in your production?

Nope, we're just storing JSONs in postgres instead now.

> is this because discord is not sending any events in the last 10 seconds?

yeah, this is normal behavior. if you continuously send events, it won't kill itself.

**Comment by spiralw** [comment]
thanks!
